# Generated by Django 3.0.4 on 2020-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockQuotes', '0005_auto_20200331_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buyPrice',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
